### ISSUE TITLE
No artefact for model

### ISSUE THREAD

**Issue by nashid** [YangLin-George/TECCD#1]
Hi there!

I would like to use the artefact from your paper. But I don't find code for the model. Are you planning to share the artefact for the model?

**Comment by LeonYang95** [comment]
Hi!

Much appreciated for your attention! 
Sorry for the delay. The first author graduated years ago and I've tried to reach out to him for this research.
I opened a new project [TECCD_Java](https://github.com/YangLin-George/TECCD_Java) to store the code he shared with me.
I hope this is helpful.
